cwd: null
data-folders:
- Graph
- Raw Data
- KSF
- Export
first-time: true
fps: 8
logs-dir: C:\cometrics\1.0.4\logs
patient-concerns: concerns.yml
phases:
- Assessment
- Treatment
recent-projects: []
window-size: []
