data-folders:
- Graph
- Raw Data
- KSF
- Export
first-time: true
logs-dir: C:\cometrics\0.12.69\logs
patient-concerns: concerns.yml
phases:
- Assessment
- Treatment
recent-projects: []
window-size: []
