data-folders:
- Graph
- Raw Data
- KSF
- Export
first-time: false
patient-concerns: concerns.yml
phases:
- Assessment
- Treatment
recent-projects:
- C:\Users\wsarc\Desktop\ExpDir\Test One
- C:\Users\wsarc\Desktop\ExpDir\Test Two
- C:\Users\wsarc\Desktop\ExpDir\Test Three
- C:\Users\wsarc\Desktop\ExpDir\Test four
- C:\Users\wsarc\Desktop\ExpDir\Play One
- C:\Users\wsarc\Desktop\ExpDir\new project twotwod
- C:\Users\wsarc\Desktop\ExpDir\Haircut Simulator
window-size:
- 864
- 1536
