data-folders:
- Graph
- Raw Data
- KSF
default-dirs:
- Functional Assessment
- Treatment
phases:
- Assessment
- Treatment
recent-projects:
- C:\Users\wsarc\Desktop\ExpDir\Haircut Simulator
window-size:
- 864
- 1536
