cwd: D:\GitHub Repos\KeystrokeAnnotator
data-folders:
- Graph
- Raw Data
- KSF
- Export
enable-ble: false
enable-e4: false
enable-review: true
enable-woodway: false
first-time: false
fps: 8
logs-dir: C:\cometrics\1.2.0\logs
patient-concerns: concerns.yml
phases:
- Assessment
- Treatment
recent-projects:
- C:\Users\wsarc\Desktop\Project Directory\Example Project
window-size:
- 864
- 1536
woodway-a-sn: FTHCUWVAA
woodway-b-sn: FTHCUQ9IA
