auto-export: true
cwd: null
data-folders:
- Graph
- Raw Data
- KSF
- Export
enable-ble: false
enable-e4: false
enable-review: false
enable-singleclick: false
enable-woodway: false
first-time: true
fps: 8
logs-dir: C:\cometrics\1.4.0\logs
patient-concerns: concerns.yml
phases:
- Assessment
- Treatment
recent-projects: []
window-size: []
woodway-a-sn: FTHCUWVAA
woodway-b-sn: FTHCUQ9IA
use-count: 0