data-folders:
- Graph
- Raw Data
- KSF
- Export
first-time: false
fps: 8
logs-dir: C:\cometrics\1.0.0\logs
patient-concerns: concerns.yml
phases:
- Assessment
- Treatment
recent-projects:
- C:\Users\wsarc\Desktop\Project Directory\Example Project
- C:\Users\wsarc\Desktop\Project Directory\Example Project 2
window-size:
- 864
- 1536
